source :rubygems

gem "middleman", "~> 3.2.0"
gem "middleman-blog", "~> 3.5.0"
gem "middleman-deploy", "~> 0.0.11"
gem "middleman-minify-html"
#gem "middleman-blog-authors", :path => '/Users/siker/dev/middleman-blog-authors' 
gem "middleman-blog-authors", :git => 'git@github.com:wireload/middleman-blog-authors.git'

# For feed.xml.builder
gem "builder", "~> 3.0.0"

gem "nokogiri"
