source :rubygems

gem "middleman", "~> 3.2.0"
gem "middleman-blog", "~> 3.5.0"
gem "middleman-deploy", "~> 0.0.11"
gem "middleman-minify-html"

# For feed.xml.builder
gem "builder", "~> 3.0.0"

gem "nokogiri"
